name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Run tests
        run: |
          echo "Running tests: $TEST"
          cat <<EOF > test.rb
          puts "Hello #{ENV['TEST']}"
          EOF
          ruby test.rb

          puts "Show exported variables"
          export
        env:
          TEST: "test"
